version: '3.8'
services:
  jenkins:
    image: "jenkins/docker"
    container_name: "jenkins"
    build: .
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ~/jenkins_home/jenkins_home:/var/jenkins_home
      - /run/host-services/docker.proxy.sock:/var/run/docker.sock
